version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: community_station_db
    volumes:
      - ./mysql/conf:/etc/mysql/conf.db
      - ./mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: community_station_dev
      MYSQL_USER: community_station
      MYSQL_PASSWORD: "community_station1234"
      TZ: "Asia/Tokyo"
